spring:
  application:
    name: lu-memory
  main:
    web-application-type: none
    banner-mode: off
    log-startup-info: false
  ai:
    mcp:
      server:
        enabled: true
        name: LU-MEMORY
        version: 0.0.1
        type: SYNC
        resource-change-notification: true
        tool-change-notification: true
        prompt-change-notification: true
  datasource:
    url: ${DB_URL:jdbc:sqlite:./lu-memory.db}
    driver-class-name: org.sqlite.JDBC
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5
      minimum-idle: 2
      idle-timeout: 300000
      max-lifetime: 1200000
      auto-commit: true
      pool-name: LuMemorySQLitePool
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      "[hibernate.format_sql]": true
      "[hibernate.dialect]": org.hibernate.community.dialect.SQLiteDialect
      "[hibernate.jdbc.batch_size]": 1
      "[hibernate.order_inserts]": true
      "[hibernate.order_updates]": true
    show-sql: false
    open-in-view: false

logging:
  file:
    name: ${LOG_FILE:logs/mcp-lu-memory-stdio-server.log}
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} %5p %c{1} - %m%n"
  level:
    root: ERROR
    com.zademy.lu_memory: INFO
    org.springframework: ERROR
    org.hibernate: ERROR
