spring:
  application:
    name: lu-memory
  main:
    web-application-type: none
    banner-mode: off
  ai:
    mcp:
      server:
        enabled: true
        name: LU-MEMORY
        version: 0.0.1
        type: SYNC
        resource-change-notification: true
        tool-change-notification: true
        prompt-change-notification: true
  datasource:
    url: jdbc:sqlite:C:/Apps/sqlite-tools-win-x64/lu-memory.db
    driver-class-name: org.sqlite.JDBC
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5
      minimum-idle: 2
      idle-timeout: 300000
      max-lifetime: 1200000
      auto-commit: false
      pool-name: LuMemorySQLitePool
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.community.dialect.SQLiteDialect
        jdbc.batch_size: 1
        order_inserts: true
        order_updates: true
    show-sql: false

logging:
  level:
    org.springframework.ai: INFO
    com.zademy.lu_memory: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    root: INFO
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/mcp-lu-memory-stdio-server.log
